export const languageOptions = [
    // {
    //     id: 63,
    //     name: "JavaScript (Node.js 12.14.0)",
    //     label: "JavaScript (Node.js 12.14.0)",
    //     value: "javascript",
    // },
    {
        id: 48,
        name: "C (GCC 7.4.0)",
        label: "C (GCC 7.4.0)",
        value: "c",
    },
    {
        id: 52,
        name: "C++ (GCC 7.4.0)",
        label: "C++ (GCC 7.4.0)",
        value: "cpp",
    },
    // {
    //     id: 51,
    //     name: "C# (Mono 6.6.0.161)",
    //     label: "C# (Mono 6.6.0.161)",
    //     value: "csharp",
    // },
    // {
    //     id: 59,
    //     name: "Fortran (GFortran 9.2.0)",
    //     label: "Fortran (GFortran 9.2.0)",
    //     value: "fortran",
    // },
    // {
    //     id: 60,
    //     name: "Go (1.13.5)",
    //     label: "Go (1.13.5)",
    //     value: "go",
    // },
    {
        id: 62,
        name: "Java (OpenJDK 13.0.1)",
        label: "Java (OpenJDK 13.0.1)",
        value: "java",
    },

    // {
    //     id: 78,
    //     name: "Kotlin (1.3.70)",
    //     label: "Kotlin (1.3.70)",
    //     value: "kotlin",
    // },
    // {
    //     id: 64,
    //     name: "Lua (5.3.5)",
    //     label: "Lua (5.3.5)",
    //     value: "lua",
    // },
    // {
    //     id: 79,
    //     name: "Objective-C (Clang 7.0.1)",
    //     label: "Objective-C (Clang 7.0.1)",
    //     value: "objectivec",
    // },
    // {
    //     id: 85,
    //     name: "Perl (5.28.1)",
    //     label: "Perl (5.28.1)",
    //     value: "perl",
    // },
    {
        id: 43,
        label: "Plain Text",
        name: "Plain Text",
        value: "text",
    },
    {
        id: 71,
        name: "Python3 (3.6.9)",
        label: "Python3 (3.6.9)",
        value: "python3",
    },
    // {
    //     id: 80,
    //     name: "R (4.0.0)",
    //     label: "R (4.0.0)",
    //     value: "r",
    // },
    // {
    //     id: 72,
    //     name: "Ruby (2.7.0)",
    //     label: "Ruby (2.7.0)",
    //     value: "ruby",
    // },
    // {
    //     id: 73,
    //     name: "Rust (1.40.0)",
    //     label: "Rust (1.40.0)",
    //     value: "rust",
    // },
    // {
    //     id: 74,
    //     name: "TypeScript (3.7.4)",
    //     label: "TypeScript (3.7.4)",
    //     value: "typescript",
    // },
];