apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  loadBalancerIP: "35.192.191.154"
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: frontend
