apiVersion: v1
kind: Service
metadata:
  name: llm-service
spec:
  type: LoadBalancer
  loadBalancerIP: "35.226.42.92"
  ports:
    - port: 80
      targetPort: 5003
      protocol: TCP
  selector:
    app: llm
