apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      containers:
      - name: app-container
        image: tianx1/dcrss-llm:v3
        ports:
            - containerPort: 5003
