apiVersion: v1
kind: Service
metadata:
  name: middleware-service
spec:
  type: LoadBalancer
  loadBalancerIP: "34.70.178.243"
  ports:
    - port: 80
      targetPort: 8085
      protocol: TCP
  selector:
    app: middleware
