apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
spec:
  replicas: 2
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
      - name: app-container
        image: tianx1/dcrss-middleware:v2
        ports:
            - containerPort: 8085
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: filestore-pvc
