apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: deployment-manager
rules:
- apiGroups: ["apps", ""]
  resources: ["deployments", "services"]
  verbs: ["create", "get", "list", "watch", "delete", "update"]
- apiGroups: ["batch"] 
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete", "update"]
