FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
  build-essential \
  gcc \
  git \
  make \
  sudo \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /home
RUN mkdir mount
WORKDIR /home/mount

CMD ["sleep", "infinity"]
